
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: snowflake_customer_purchases
    description: "the total purchses for each customer in snowflake sample data"
    columns:
      - name: C_CUSTKEY
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: cumulative_orders_by_date.sql
    description: "the total purchses acumulatives"
    columns:
      - name: o_orderdate
        description: "acumulatives sales date "
        tests:
          - unique
          - not_null
  - name: incremental_time.sql
  - name : playing_with_tests
    description: "A starter dbt model"
    columns:
      - name: c_mktsegment
        description: "The primary key for this table"
        tests:
          - accepted_values:
              values: ['AUTOMOBILE', 'MACHINERY', 'HOUSEHOLD', 'FURNITURE']
